apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/khoaihps/Documents/Code/GR2/airflow
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      volumes:
        - name: airflow-volume
          persistentVolumeClaim:
            claimName: airflow-pvc
      containers:
        - name: airflow
          image: apache/airflow:2.6.0
          command: ["airflow"]
          args: ["webserver"]
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://postgres:postgres@postgresql:5432/airflow"
          volumeMounts:
            - mountPath: /opt/airflow
              name: airflow-volume
          ports:
            - containerPort: 8080
