apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init
spec:
  template:
    spec:
      containers:
        - name: airflow-db-init
          image: apache/airflow:2.6.0
          command: ["airflow"]
          args: ["db", "init"]
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://postgres:postgres@postgresql:5432/airflow"
      restartPolicy: Never
