apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-tick-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-tick-streaming
  template:
    metadata:
      labels:
        app: binance-tick-streaming
    spec:
      containers:
        - name: binance-tick-streaming
          image: khoaihps1/binance-tick-streaming:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: binance-tick-streaming-service
spec:
  selector:
    app: binance-tick-streaming
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
