apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-bot
  template:
    metadata:
      labels:
        app: order-bot
    spec:
      containers:
        - name: order-bot
          image: khoaihps1/order-bot:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-bot-service
spec:
  selector:
    app: order-bot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
